version: '3.8'

services:
  copilot-backend:
    image: ghcr.io/deki60/copilot-backend:latest
    ports:
      - "5000:5000"  # Expose le port 5000 pour le développement
    volumes:
      - ./data/copilot-backend-data/logs:/opt/logs
      - ./data/data:/opt/copilot/backend/data
      - ./backend:/app  # Synchronise le code source local avec le conteneur
    env_file: .env
    depends_on:
      - copilot-mysql
    restart: always

  copilot-frontend:
    image: ghcr.io/deki60/copilot-frontend:latest
    environment:
      - SERVER_HOST=localhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app  # Synchronise le frontend avec le conteneur
    restart: always

  copilot-mysql:
    image: mysql:8.0.38-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: copilot
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
