version: "3.3"

services:
  copilot-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile    # Assurez-vous que ce Dockerfile est celui utilisé pour le backend
    ports:
      - "5000:5000"  # Le backend reste accessible sur le port 5000
    volumes:
      - ./data/copilot-backend-data/logs:/opt/logs
      - ./data/data:/opt/copilot/backend/data
      - ./backend:/opt/copilot/backend   # Montage du code source du backend pour modification live
    env_file: .env
    depends_on:
      - copilot-mysql
    restart: always

  copilot-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile    # Assurez-vous que ce Dockerfile est celui utilisé pour le frontend
    environment:
      - SERVER_HOST=${SERVER_HOST:-localhost}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app   # Montage du code source du frontend pour modification live
    restart: always

  copilot-mysql:
    image: mysql:8.0.38-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: copilot
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  copilot-minio:
    image: quay.io/minio/minio:RELEASE.2024-09-13T20-26-02Z
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
    volumes:
      - ./data/data/minio-data:/data
    command: server /data --console-address ":9001"
    restart: always

  copilot-nuclei-module:
    image: ghcr.io/socfortress/copilot-nuclei-module:latest
    restart: always

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
